# Generated by Django 4.2.4 on 2023-08-31 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='ni',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(9999999999)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(999999999999)),
        ),
    ]
