# Generated by Django 4.2.4 on 2023-08-31 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_movimientos', '0002_alter_armamento_ni_alter_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='ni',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(limit_value=9999999999)),
        ),
    ]
