# Generated by Django 4.2.4 on 2023-08-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_movimientos', '0003_alter_armamento_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='ni',
            field=models.IntegerField(),
        ),
    ]
