# Generated by Django 4.2.4 on 2023-08-31 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_movimientos', '0004_alter_armamento_ni'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamento',
            name='tipo',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armamento',
            name='ni',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(limit_value=9999999999)),
        ),
    ]
