# Generated by Django 4.2.4 on 2023-08-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_movimientos', '0005_armamento_tipo_alter_armamento_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='ni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
